import { Suspense } from 'react';
import { Metadata } from 'next';
import './globals.css';
import { AuthProvider } from '../contexts/AuthContext';
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata: Metadata = {
  title: 'Likes.mn - Social Media Marketing Services',
  description: 'High quality social media marketing services for Instagram, TikTok, YouTube and more.',
  icons: {
    icon: [
      { url: '/add-friend.png', sizes: '64x64', type: 'image/png' },
   
    ],
    apple: [
      { url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
    ],
  },
  manifest: '/manifest.json',
};

// Make sure pages can be statically generated by using a static auth provider
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<div>Loading...</div>}>
          <AuthProvider>
            {children}
            <footer className="bg-white py-8 mt-auto">
              <div className="max-w-6xl mx-auto px-4 text-center">
                <div className="flex justify-center space-x-4 text-sm text-gray-600">
                  <a href="/terms" className="hover:text-purple-600 transition-colors">
                    Үйлчилгээний нөхцөл
                  </a>
                </div>
                <p className="mt-4 text-sm text-gray-500">
                  © {new Date().getFullYear()} likes.mn - Бүх эрх хуулиар хамгаалагдсан.
                </p>
              </div>
            </footer>
          </AuthProvider>
        </Suspense>
        <SpeedInsights />
      </body>
    </html>
  );
} 