import { Suspense } from 'react';
import { Metadata } from 'next';
import './globals.css';
import { AuthProvider } from '../contexts/AuthContext';
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata: Metadata = {
  title: 'Likes.mn - Social Media Marketing Services',
  description: 'High quality social media marketing services for Instagram, TikTok, YouTube and more.',
  icons: {
    icon: [
      { url: '/add-friend.png', sizes: '64x64', type: 'image/png' },
   
    ],
    apple: [
      { url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
    ],
  },
  manifest: '/manifest.json',
};

// Make sure pages can be statically generated by using a static auth provider
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<div>Loading...</div>}>
          <AuthProvider>
            {children}
          </AuthProvider>
        </Suspense>
        <SpeedInsights />
      </body>
    </html>
  );
} 